[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/yamux"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"

[[constraint]]
  branch = "master"
  name = "github.com/mohae/deepcopy"

[[constraint]]
  name = "github.com/coreos/go-semver"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/copier"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"
