version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/nimona/go-nimona
    environment:
      CIRCLE_TEST_REPORTS: /tmp/test-reports
      CIRCLE_ARTIFACTS: /tmp/artifacts
    steps:
      - checkout
      - run:
          name: Install tools
          command: |
            go get -u github.com/golang/dep/cmd/dep
            go get -u github.com/axw/gocov/gocov
            go get -u github.com/mattn/goveralls
            go get -u github.com/jstemmer/go-junit-report
      - run:
          name: Install dependencies
          command: dep ensure
      - run:
          name: Build everything
          command: go build -v ./...
      - run:
          name: Run tests
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS
            mkdir -p $CIRCLE_ARTIFACTS
            go test -race -v -coverprofile=$CIRCLE_ARTIFACTS/profile.out | go-junit-report > $CIRCLE_TEST_REPORTS/junit.xml
            sed -i "/_mock/d" $CIRCLE_ARTIFACTS/profile.out
      - run:
          name: Upload to coveralls
          command: goveralls -coverprofile=$CIRCLE_ARTIFACTS/profile.out -service=circle-ci -repotoken=$COVERALLS_TOKEN