version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/nimona/go-nimona
    steps:
      - checkout
      - run:
          name: Install dep
          command: go get -u github.com/golang/dep/cmd/dep
      - run:
          name: Install gocov
          command: go get -u github.com/axw/gocov/gocov
      - run:
          name: Install goveralls
          command: go get -u github.com/mattn/goveralls
      - run:
          name: Install dependencies
          command: dep ensure
      - run:
          name: Run tests
          command: |
            make test-cover
            goveralls -v -coverprofile=coverage.txt -service=circle-ci -repotoken=$COVERALLS_TOKEN
